"""Session Bridge MCP Server - FastMCP interface for LLM access."""

import json
import sys
import os
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from mcp.server.fastmcp import FastMCP
from pydantic import BaseModel, ConfigDict, Field
from core.models import Session
from core.database import SessionDatabase, SessionLimitReachedError, _MAX_IMPORT_BYTES, _MAX_SESSIONS_PER_FILE, _IMPORT_FIELD_CAPS
from core.config import Config, set_tier as _set_tier_config
from core.license import get_license_status
from core.onboard_tool import run_onboard as _run_onboard, _config_path as _onboard_config_path

mcp = FastMCP(
    "loreconvo",
    instructions=(
        "LoreConvo provides persistent memory across Claude sessions. "
        "Use save_session to vault decisions and context. "
        "Use search_sessions or get_context_for to recall prior work. "
        "Use get_recent_sessions to see what was done recently. "
        "Use vault_suggest to get proactive recommendations on what to revisit. "
        "Use loreconvo_onboard to set up your workspace on first install. "
        "Fields: surface identifies the platform (code/cowork/chat/codex/custom), "
        "project is a snake_case workspace identifier, "
        "tags use conventions status:*, priority:*, agent:* (see your setup doc), "
        "skills_used lists skill names invoked (not tool names). "
        "Agents tag sessions with agent:<name> -- not the surface field."
    )
)

db = SessionDatabase(Config())


def _compress_summary(raw_summary: str) -> str:
    """Compress raw_summary via Claude API. Returns raw on any failure (no key, import error, API error)."""
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        return raw_summary
    try:
        import anthropic
    except ImportError:
        return raw_summary
    try:
        client = anthropic.Anthropic(api_key=api_key)
        response = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=1024,
            messages=[{
                "role": "user",
                "content": (
                    "Summarize the following session notes concisely. "
                    "Preserve all key decisions, artifacts, and open questions. "
                    "Output only the summary text:\n\n" + raw_summary
                ),
            }],
        )
        return response.content[0].text
    except Exception:
        return raw_summary


@mcp.tool(title="Save Session")
def save_session(
    title: str,
    surface: str,
    summary: str,
    decisions: list[str] | None = None,
    artifacts: list[str] | None = None,
    open_questions: list[str] | None = None,
    tags: list[str] | None = None,
    skills_used: list[str] | None = None,
    project: str | None = None,
    start_date: str | None = None,
    end_date: str | None = None,
    session_id: str | None = None,
    external_tool_session: bool = False,
    summarize: bool = False,
) -> dict:
    """Save a session summary to persistent memory.

    Call this at the end of a session or when the user requests /bridge save.
    Captures decisions, artifacts, skills used, and open questions for recall
    in future sessions.

    Args:
        title: Short descriptive title for the session
        surface: Where this session ran - 'cowork', 'code', or 'chat'
        summary: 2-3 paragraph narrative summary of what happened
        decisions: List of key decisions made during the session
        artifacts: List of files created or modified
        open_questions: Unresolved questions to carry forward
        tags: Freeform tags for categorization
        skills_used: Skills that were invoked during this session
        project: Project name if part of a defined project
        start_date: ISO 8601 start time (defaults to now)
        end_date: ISO 8601 end time
        session_id: Optional session ID to enable deduplication with the
            auto-save hook. If a session with this ID already exists (e.g.,
            auto-saved at session end), the record is updated with the richer
            manual metadata. Artifacts from the existing record are preserved
            when the caller does not supply artifacts. If omitted, a new UUID
            is generated (existing behavior).
        external_tool_session: Set True when saving a session generated by an
            external tool (e.g., Anthropic Managed Agents). Flagged sessions are
            excluded from auto-load and search by default to prevent context
            contamination. Override exclusion with include_external=True on search,
            or set LORECONVO_EXTERNAL_TOOL_EXCLUSION=0 to disable globally.
        summarize: If True and ANTHROPIC_API_KEY is set, send the summary to
            Claude API (Haiku) for compression before saving. Opt-in only;
            defaults to False. Falls back to the raw summary on any API error
            or if the key is absent. See INSTALL.md Privacy Note.
    """
    if summarize:
        summary = _compress_summary(summary)

    # Merge artifacts with any existing auto-saved record when session_id is known
    merged_artifacts = artifacts or []
    if session_id is not None and not artifacts:
        existing = db.get_session(session_id)
        if existing and existing.artifacts:
            merged_artifacts = existing.artifacts

    session = Session(
        title=title,
        surface=surface,
        summary=summary,
        decisions=decisions or [],
        artifacts=merged_artifacts,
        open_questions=open_questions or [],
        tags=tags or [],
        skills_used=skills_used or [],
        project=project,
        external_tool_session=external_tool_session,
    )
    if session_id is not None:
        session.id = session_id
    if start_date:
        session.start_date = start_date
    if end_date:
        session.end_date = end_date

    try:
        saved_id = db.save_session(session)
    except SessionLimitReachedError as e:
        return {
            "status": "limit_reached",
            "error": str(e),
            "upgrade_url": "https://labyrinthanalyticsconsulting.com/loreconvo",
        }

    # first-use nudge
    config_exists = _onboard_config_path(db).exists()
    is_first_session = db.session_count() == 1 and not config_exists

    result = {"session_id": saved_id, "status": "saved", "title": title}
    if is_first_session:
        result["setup_tip"] = (
            "First session detected. Run loreconvo_onboard() to set up tag "
            "conventions, project structure, and get a reference doc for your "
            "AI assistant."
        )
    return result


@mcp.tool(title="Get Recent Sessions")
def get_recent_sessions(
    limit: int = 10,
    days_back: int = 30,
    project: str | None = None,
    skill: str | None = None,
) -> list[dict]:
    """Get recent session summaries.

    Use to see what work was done recently, optionally filtered by project or skill.

    Args:
        limit: Max sessions to return (default 10)
        days_back: How far back to look (default 30 days)
        project: Filter to sessions in this project
        skill: Filter to sessions that used this skill
    """
    sessions = db.get_recent_sessions(limit, days_back, project, skill)
    return [
        {
            "id": s.id,
            "title": s.title,
            "surface": s.surface,
            "project": s.project,
            "date": s.start_date,
            "summary_preview": s.summary[:200] + "..." if len(s.summary) > 200 else s.summary,
            "decision_count": len(s.decisions),
            "skills": s.skills_used,
        }
        for s in sessions
    ]


@mcp.tool(title="Get Session")
def get_session(session_id: str) -> dict:
    """Get full details of a specific session.

    Args:
        session_id: The UUID of the session to retrieve
    """
    session = db.get_session(session_id)
    if not session:
        return {"error": f"Session {session_id} not found"}
    return {
        "id": session.id,
        "title": session.title,
        "surface": session.surface,
        "project": session.project,
        "start_date": session.start_date,
        "end_date": session.end_date,
        "summary": session.summary,
        "decisions": session.decisions,
        "artifacts": session.artifacts,
        "open_questions": session.open_questions,
        "tags": session.tags,
        "skills_used": session.skills_used,
    }


@mcp.tool(title="Search Sessions")
def search_sessions(
    query: str,
    persona: str | None = None,
    tags: list[str] | None = None,
    skills: list[str] | None = None,
    project: str | None = None,
    limit: int = 10,
    include_external: bool = False,
    semantic: bool = False,
) -> list[dict]:
    """Search session memory by keyword, with optional filters.

    Use to find sessions where a topic was discussed, a decision was made,
    or a specific skill/project was involved.

    Args:
        query: Search keywords (matched against title, summary, decisions)
        persona: Filter to sessions tagged with this persona (supports prefix matching)
        tags: Filter to sessions with any of these tags
        skills: Filter to sessions that used any of these skills
        project: Filter to sessions in this project
        limit: Max results (default 10)
        include_external: If True, include sessions flagged as external_tool_session.
            Default False. Can also be enabled globally via LORECONVO_EXTERNAL_TOOL_EXCLUSION=0.
        semantic: If True, use LanceDB hybrid (vector + BM25) search instead of FTS5.
            Pro tier only. Falls back to FTS5 if index not built yet; run
            rebuild_index to build it after first Pro activation.
    """
    results = db.search_sessions(query, persona, tags, skills, project, limit, include_external=include_external, semantic=semantic)
    return [
        {
            "id": r.session.id,
            "title": r.session.title,
            "date": r.session.start_date,
            "surface": r.session.surface,
            "project": r.session.project,
            "summary_preview": r.session.summary[:300] + "..." if len(r.session.summary) > 300 else r.session.summary,
            "decisions": r.session.decisions,
            "match_score": r.match_score,
        }
        for r in results
    ]


@mcp.tool(title="Get Context for Topic")
def get_context_for(
    topic: str,
    max_results: int = 5,
    include_external: bool = False,
    semantic: bool = False,
) -> list[dict]:
    """Get relevant session context for a topic.

    Use at the start of a session to load prior decisions and context about a topic.
    Returns the most relevant session excerpts.

    Args:
        topic: The topic to find context for (e.g., 'K-1 parser', 'rental insurance')
        max_results: Max excerpts to return (default 5)
        include_external: If True, include sessions flagged as external_tool_session.
            Default False.
        semantic: If True, use LanceDB hybrid search (Pro only). Falls back to FTS5
            if index not yet built.
    """
    results = db.get_context_for(topic, max_results, include_external=include_external, semantic=semantic)
    return [
        {
            "session_title": r.session.title,
            "date": r.session.start_date,
            "summary": r.session.summary,
            "decisions": r.session.decisions,
            "open_questions": r.session.open_questions,
            "match_score": r.match_score,
        }
        for r in results
    ]


@mcp.tool(title="Tag Session")
def tag_session(
    session_id: str,
    persona_name: str,
    relevance_note: str | None = None,
) -> dict:
    """Tag a session with a persona for filtered recall.

    Supports hierarchical personas (e.g., 'ron-bot:sql' matches 'ron-bot' queries).

    Args:
        session_id: Session to tag
        persona_name: Persona identifier (e.g., 'ron-bot', 'ron-bot:sql', 'tax-prep')
        relevance_note: Optional note about why this session is relevant to the persona
    """
    db.tag_session(session_id, persona_name, relevance_note)
    return {"status": "tagged", "session_id": session_id, "persona": persona_name}


@mcp.tool(title="Link Sessions")
def link_sessions(
    from_id: str,
    to_id: str,
    link_type: str = "continues",
) -> dict:
    """Link two related sessions.

    Args:
        from_id: Source session ID
        to_id: Target session ID
        link_type: Relationship type - 'continues', 'related', or 'supersedes'
    """
    db.link_sessions(from_id, to_id, link_type)
    return {"status": "linked", "from": from_id, "to": to_id, "type": link_type}


@mcp.tool(title="Get Related Sessions")
def get_related_sessions(
    session_id: str,
    limit: int = 10,
    min_shared_terms: int = 3,
) -> dict:
    """Find sessions related to a given session by keyword co-occurrence. Pro only.

    Analyzes the keyword index built during save_session to surface sessions
    that share the most terms with the given session. Useful for discovering
    related work across projects and time periods.

    Args:
        session_id: UUID of the session to find related sessions for
        limit: Max results to return (default 10, max 50)
        min_shared_terms: Minimum shared keywords required (default 3)
    """
    status = get_license_status()
    if not status["is_pro"]:
        return {
            "error": (
                "get_related_sessions requires LoreConvo Pro. "
                "Set your LORECONVO_PRO license key or contact "
                "info@labyrinthanalyticsconsulting.com to upgrade."
            )
        }
    limit = max(1, min(limit, 50))
    related = db.get_related_sessions(session_id, limit, min_shared_terms)
    return {
        "session_id": session_id,
        "related_count": len(related),
        "related": related,
    }


@mcp.tool(title="Rebuild Semantic Index")
def rebuild_index() -> dict:
    """Rebuild the LanceDB semantic search index from all stored sessions. Pro only.

    Run after first Pro activation, or to recover from a corrupted index.
    Downloads BAAI/bge-small-en-v1.5 (~130MB) once on first run; subsequent
    runs use the cached model. May take 1-2 minutes for large session stores.

    Returns a dict with 'indexed' (sessions added to index) and 'total_in_db'
    (total sessions in SQLite, including those excluded from indexing).
    """
    status = get_license_status()
    if not status["is_pro"]:
        return {
            "error": (
                "rebuild_index requires LoreConvo Pro. "
                "Get a license at labyrinthanalyticsconsulting.com."
            )
        }
    return db.rebuild_lance_index()


@mcp.tool(title="Get Project")
def get_project(project_name: str) -> dict:
    """Get project details including recent sessions and skill usage stats.

    Args:
        project_name: The project identifier
    """
    result = db.get_project(project_name)
    if not result:
        return {"error": f"Project '{project_name}' not found"}
    return result


@mcp.tool(title="List Projects")
def list_projects() -> list[dict]:
    """List all defined projects with session counts."""
    return db.list_projects()


@mcp.tool(title="Create Project")
def create_project(
    name: str,
    description: str = "",
    expected_skills: list[str] | None = None,
    default_persona: str | None = None,
) -> dict:
    """Create or update a project definition.

    Projects group related sessions and can auto-associate based on skill usage.

    Args:
        name: Project identifier (e.g., 'secret-agent-man', 'project-ron')
        description: What this project is about
        expected_skills: Skills typically used in this project's sessions
        default_persona: Auto-tag new sessions with this persona
    """
    db.create_project(name, description, expected_skills, default_persona)
    return {"status": "created", "project": name}


@mcp.tool(title="Onboard LoreConvo")
def loreconvo_onboard(
    name: str | None = None,
    projects: list[str] | None = None,
    agents: list[str] | None = None,
    tag_style: str = "simple",
) -> dict:
    """Set up or update your LoreConvo workspace configuration.

    Call this once after installing LoreConvo to get a recommended setup.
    Call again any time to add projects or agents, or to regenerate your
    reference doc.

    Creates:
    - Project registrations for each project listed
    - A config file at ~/.loreconvo/onboard_config.json
    - A reference doc (markdown) in the response -- paste it into your
      CLAUDE.md or a LoreDocs vault so your AI assistant can apply your
      conventions consistently

    Args:
        name: Your workspace or team name (e.g. 'Labyrinth Analytics')
        projects: Snake_case project identifiers (e.g. ['side_hustle', 'finance'])
        agents: Agent names that will tag sessions (e.g. ['ron', 'meg'])
        tag_style: 'simple' (status + priority) or 'detailed' (adds effort,
                   scout-run markers, date tag guidance)

    Surfaces: code (Claude Code), cowork (Claude.ai Projects), chat (Claude.ai
    chat), codex (Codex CLI). Custom values are allowed for other tools.
    Agent identity: use tags=['agent:name'] -- not the surface field.
    """
    if tag_style not in ("simple", "detailed"):
        return {"error": "tag_style must be 'simple' or 'detailed'"}
    return _run_onboard(db, name=name, projects=projects, agents=agents, tag_style=tag_style)


@mcp.tool(title="Get Skill History")
def get_skill_history(
    skill_name: str,
    days_back: int = 90,
) -> list[dict]:
    """Get all sessions that used a specific skill.

    Useful for understanding how often a skill is used and in what contexts.

    Args:
        skill_name: The skill to look up (e.g., 'rental-property-accounting')
        days_back: How far back to search (default 90 days)
    """
    sessions = db.get_skill_history(skill_name, days_back)
    return [
        {
            "id": s.id,
            "title": s.title,
            "date": s.start_date,
            "surface": s.surface,
            "project": s.project,
        }
        for s in sessions
    ]


@mcp.tool(title="Get Context Suggestions")
def vault_suggest(
    project: str | None = None,
    persona: str | None = None,
    days_back: int = 14,
    limit: int = 5,
) -> dict:
    """Get proactive context suggestions based on your session history.

    Analyzes recent sessions and surfaces:
    - Sessions with unresolved open questions that need follow-up
    - Sessions with key decisions worth reviewing before starting new work
    - Skill gaps: skills expected by a project but not used recently

    Use at the start of a session to find the most valuable prior context,
    or when you're unsure what to work on next.

    Args:
        project: Filter suggestions to this project
        persona: Filter to sessions tagged with this persona (prefix matching)
        days_back: How far back to look (default 14 days)
        limit: Max suggestions to return (default 5)
    """
    return db.get_suggestions(project, persona, days_back, limit)


@mcp.tool(title="Get License Tier")
def get_tier() -> dict:
    """Return the current LoreConvo license tier and status.

    Use this to confirm whether the Pro license key is loaded and valid.

    Returns a dict with keys:
        is_pro  -- bool, True if Pro tier is active
        mode    -- "licensed" | "dev_bypass" | "free" | "invalid_key"
        product -- product name from the license payload (if licensed)
        exp     -- expiry date or "never" (if licensed)
        email   -- customer email (if licensed and present)
        error   -- error message (if mode is "invalid_key")
    """
    return get_license_status()


class VaultSetTierInput(BaseModel):
    model_config = ConfigDict(str_strip_whitespace=True)
    tier: str = Field(
        ...,
        description="Tier to activate: 'free' or 'pro'",
        pattern="^(free|pro)$"
    )


@mcp.tool(
    title="Set License Tier",
    name="vault_set_tier",
    annotations={"readOnlyHint": False, "destructiveHint": False, "idempotentHint": True, "openWorldHint": False}
)
def vault_set_tier(params: VaultSetTierInput) -> str:
    """Activate a tier (free or pro) for LoreConvo.

    Pro tier removes the free-tier session limit (default: 50 sessions).
    After purchasing a Pro license, set LORECONVO_PRO=<your-license-key> in
    your environment and restart the server, then call this tool with tier='pro'
    to confirm Pro is active. Reverting to tier='free' re-enables limits (existing
    sessions are preserved -- only new saves are blocked once the limit is hit).
    """
    if params.tier == "pro":
        status = get_license_status()
        if not status["is_pro"]:
            if status.get("mode") == "invalid_key":
                return (
                    "Error: Invalid or expired license key in LORECONVO_PRO. "
                    + status.get("error", "")
                    + " Get a new key at labyrinthanalyticsconsulting.com."
                )
            return (
                "Error: No Pro license key found. "
                "Set LORECONVO_PRO=<your-license-key> in your environment and "
                "restart the server, then call vault_set_tier again. "
                "Get a license key at labyrinthanalyticsconsulting.com."
            )

    db_dir = Path(db.config.db_path).parent
    try:
        _set_tier_config(db_dir, params.tier)
    except ValueError as exc:
        return f"Error: {exc}"

    if params.tier == "pro":
        return "[OK] Tier set to 'pro'. All limits removed. Enjoy unlimited sessions."
    return (
        f"[OK] Tier set to 'free'. Free tier active. "
        f"Limit: {db.config.max_free_sessions} sessions."
    )


@mcp.tool(title="Export Sessions")
def export_sessions(
    output_path: str | None = None,
    project: str | None = None,
    tags: list[str] | None = None,
    days_back: int | None = None,
    limit: int = 1000,
    format: str = "json",
) -> dict:
    """Export sessions to JSON or JSONL for backup or migration.

    Exports all matching sessions with full detail (including skills, tags,
    artifacts). Use output_path to write to a file; omit it to receive the
    data inline. Use import_sessions to load the exported file.

    Args:
        output_path: File path to write export (e.g. '/tmp/loreconvo_export.json').
                     If omitted, data is returned inline.
        project: Export only sessions from this project.
        tags: Export only sessions that have any of these tags.
        days_back: Limit to sessions from the last N days. Omit for all time.
        limit: Max sessions to export (default 1000).
        format: 'json' (array wrapped in metadata) or 'jsonl' (one session per line).
    """
    sessions = db.get_sessions_for_export(
        project=project, tags=tags, days_back=days_back, limit=limit
    )

    def _session_to_dict(s) -> dict:
        return {
            "id": s.id,
            "title": s.title,
            "surface": s.surface,
            "project": s.project,
            "start_date": s.start_date,
            "end_date": s.end_date,
            "summary": s.summary,
            "decisions": s.decisions,
            "artifacts": s.artifacts,
            "open_questions": s.open_questions,
            "tags": s.tags,
            "skills_used": s.skills_used,
            "created_at": s.created_at,
        }

    session_dicts = [_session_to_dict(s) for s in sessions]

    if format == "jsonl":
        data_str = "\n".join(json.dumps(d) for d in session_dicts)
    else:
        export_obj = {
            "loreconvo_export": {
                "version": "1.0",
                "session_count": len(session_dicts),
                "filters": {
                    "project": project,
                    "tags": tags,
                    "days_back": days_back,
                },
                "sessions": session_dicts,
            }
        }
        data_str = json.dumps(export_obj, indent=2)

    if output_path:
        resolved = Path(output_path).expanduser().resolve()
        home = Path.home().resolve()
        if not str(resolved).startswith(str(home)):
            return {"error": "output_path must be within the home directory"}
        if resolved.suffix.lower() not in (".json", ".jsonl"):
            return {"error": "output_path must end with .json or .jsonl"}
        resolved.write_text(data_str, encoding="utf-8")
        return {
            "status": "exported",
            "path": str(resolved),
            "session_count": len(sessions),
            "format": format,
        }

    return {
        "status": "exported",
        "session_count": len(sessions),
        "format": format,
        "data": data_str,
    }


@mcp.tool(title="Export Sessions for Anthropic")
def export_for_anthropic(
    output_path: str | None = None,
    project: str | None = None,
    session_ids: list[str] | None = None,
    days_back: int | None = None,
) -> dict:
    """Export LoreConvo sessions to Anthropic managed-agents memory format. Pro only.

    Produces a JSON file in 'anthropic-memory-v1' format, suitable for import into
    Anthropic managed-agents memory stores. Only non-periodic, non-file-memory sessions
    are exported (contamination control).

    NOTE: Field mapping is preliminary pending Anthropic beta API schema stabilization.
    Cassandra will signal when the schema is stable. Save the output and validate
    against Anthropic docs before submitting to a managed-agents memory store.

    Args:
        output_path: File path to write the export. If omitted, data is returned inline.
        project: Export only sessions from this project.
        session_ids: List of specific session UUIDs to export. Overrides project filter.
        days_back: Limit to sessions from the last N days.
    """
    from datetime import datetime, timedelta, timezone as _tz

    status = get_license_status()
    if not status["is_pro"]:
        return {
            "error": (
                "Export to Anthropic format requires LoreConvo Pro. "
                "Get a license at labyrinthanalyticsconsulting.com."
            )
        }

    sessions = db.get_sessions_for_shared_export(
        project=project,
        session_id_filter=session_ids,
        export_all=(session_ids is None and project is None),
    )

    if days_back is not None:
        cutoff = (datetime.now(_tz.utc) - timedelta(days=days_back)).isoformat().replace('+00:00', 'Z')
        sessions = [s for s in sessions if s.start_date >= cutoff]

    entries = []
    for s in sessions:
        entries.append({
            "id": s.id,
            "content": s.summary or "",
            "created_at": s.created_at,
            "tags": s.tags or [],
            "metadata": {
                "title": s.title,
                "surface": s.surface,
                "project": s.project,
            },
        })

    export_obj = {
        "format": "anthropic-memory-v1",
        "source": "loreconvo",
        "exported_at": datetime.now(_tz.utc).isoformat().replace("+00:00", "Z"),
        "schema_note": (
            "Preliminary field mapping -- validate against Anthropic beta API "
            "docs before submitting to Anthropic memory stores."
        ),
        "entry_count": len(entries),
        "entries": entries,
    }

    data_str = json.dumps(export_obj, indent=2)

    if output_path:
        resolved = Path(output_path).expanduser().resolve()
        home = Path.home().resolve()
        if not str(resolved).startswith(str(home)):
            return {"error": "output_path must be within the home directory"}
        if resolved.suffix.lower() != ".json":
            return {"error": "output_path must end with .json"}
        resolved.write_text(data_str, encoding="utf-8")
        return {
            "status": "exported",
            "format": "anthropic-memory-v1",
            "path": str(resolved),
            "entry_count": len(entries),
        }

    return {
        "status": "exported",
        "format": "anthropic-memory-v1",
        "entry_count": len(entries),
        "data": data_str,
    }


@mcp.tool(title="Import Sessions")
def import_sessions(
    file_path: str,
    on_conflict: str = "skip",
    dry_run: bool = False,
) -> dict:
    """Import sessions from a LoreConvo export file (JSON or JSONL).

    Reads an export created by export_sessions and saves sessions into the
    local database. Session UUIDs are preserved so re-importing is safe.

    Args:
        file_path: Path to the export file (JSON or JSONL format).
        on_conflict: What to do if a session ID already exists.
                     'skip' (default) -- leave the existing session unchanged.
                     'replace' -- overwrite with the imported version.
        dry_run: If True, parse and validate the file but make no DB changes.
    """
    if on_conflict not in ("skip", "replace"):
        return {"error": "on_conflict must be 'skip' or 'replace'"}

    path = Path(file_path)
    if not path.exists():
        return {"error": f"File not found: {file_path}"}

    if path.stat().st_size > _MAX_IMPORT_BYTES:
        return {"error": "Import file too large. Max: 50 MB."}

    raw = path.read_text(encoding="utf-8").strip()

    raw_sessions: list[dict] = []
    # Try JSON format with wrapper first
    try:
        wrapper = json.loads(raw)
        if "loreconvo_export" in wrapper:
            raw_sessions = wrapper["loreconvo_export"]["sessions"]
        elif isinstance(wrapper, dict) and ("id" in wrapper or "title" in wrapper):
            # Single-session JSONL: one JSON object that is valid JSON on its own
            raw_sessions = [wrapper]
        else:
            return {"error": "Invalid export file: missing 'loreconvo_export' key"}
    except json.JSONDecodeError:
        # Fall back to JSONL -- one session per line
        for line_num, line in enumerate(raw.splitlines(), 1):
            line = line.strip()
            if not line:
                continue
            try:
                raw_sessions.append(json.loads(line))
            except json.JSONDecodeError as exc:
                return {"error": f"Invalid JSON on line {line_num}: {exc}"}

    if len(raw_sessions) > _MAX_SESSIONS_PER_FILE:
        return {"error": "Import file contains too many sessions. Max: 10,000."}

    imported = 0
    replaced = 0
    skipped = 0
    limit_hit = False

    for raw_s in raw_sessions:
        title = str(raw_s.get("title", "") or "")[:_IMPORT_FIELD_CAPS["title"]]
        summary = str(raw_s.get("summary", "") or "")[:_IMPORT_FIELD_CAPS["summary"]]
        decisions = [str(d)[:_IMPORT_FIELD_CAPS["list_item"]] for d in (raw_s.get("decisions") or [])]
        open_questions = [str(q)[:_IMPORT_FIELD_CAPS["list_item"]] for q in (raw_s.get("open_questions") or [])]
        tags = [str(t)[:_IMPORT_FIELD_CAPS["list_item"]] for t in (raw_s.get("tags") or [])]
        artifacts = [Path(str(a)).name for a in (raw_s.get("artifacts") or [])]
        skills_used = [str(s)[:_IMPORT_FIELD_CAPS["list_item"]] for s in (raw_s.get("skills_used") or [])]
        session = Session(
            id=raw_s.get("id", ""),
            title=title,
            surface=raw_s.get("surface", ""),
            project=raw_s.get("project"),
            start_date=raw_s.get("start_date", ""),
            end_date=raw_s.get("end_date"),
            summary=summary,
            decisions=decisions,
            artifacts=artifacts,
            open_questions=open_questions,
            tags=tags,
            skills_used=skills_used,
            created_at=raw_s.get("created_at", ""),
        )
        if not session.id:
            skipped += 1
            continue

        if dry_run:
            if db.session_exists(session.id):
                if on_conflict == "replace":
                    replaced += 1
                else:
                    skipped += 1
            else:
                imported += 1
            continue

        try:
            result = db.import_session(session, replace=(on_conflict == "replace"))
        except SessionLimitReachedError:
            limit_hit = True
            break

        if result == "imported":
            imported += 1
        elif result == "replaced":
            replaced += 1
        else:
            skipped += 1

    summary = {
        "status": "dry_run" if dry_run else "done",
        "total_in_file": len(raw_sessions),
        "imported": imported,
        "replaced": replaced,
        "skipped": skipped,
    }
    if dry_run:
        summary["note"] = (
            f"Dry run preview: {imported} would-import, {replaced} would-replace, "
            f"{skipped} would-skip. No changes made."
        )
    if limit_hit:
        summary["warning"] = (
            "Free tier limit reached. Some sessions were not imported. "
            "Upgrade to Pro for unlimited sessions."
        )
    return summary


@mcp.tool(title="Inspect Sessions")
def inspect_sessions(
    session_id: str | None = None,
    search: str | None = None,
    tag: str | None = None,
    surface: str | None = None,
    since: str | None = None,
    limit: int = 20,
    show_stats: bool = False,
) -> dict:
    """Inspect stored sessions: list, filter, or get full detail for one session.

    Answers 'what do you know about me?' and helps users find, browse, and
    understand their stored session memory.

    Args:
        session_id: If provided, return full detail for this specific session.
        search: Full-text search query across title, summary, decisions, tags.
        tag: Filter by tag substring (e.g. 'agent:ron', 'side_hustle').
        surface: Filter by surface ('code', 'cowork', 'chat').
        since: Return sessions on or after this date (YYYY-MM-DD).
        limit: Max sessions to return (default 20).
        show_stats: If True, include aggregate counts (total, by_surface, by_project).
    """
    if session_id:
        session = db.get_session(session_id)
        if not session:
            return {"error": f"Session {session_id} not found"}
        return {
            "id": session.id,
            "title": session.title,
            "date": session.start_date[:16] if session.start_date else "",
            "surface": session.surface,
            "project": session.project,
            "tags": session.tags,
            "summary": session.summary,
            "decisions": session.decisions,
            "artifacts": session.artifacts,
            "open_questions": session.open_questions,
            "skills_used": session.skills_used,
        }

    sessions = db.inspect_sessions(
        search=search, tag=tag, surface=surface, since=since, limit=limit
    )

    result: dict = {
        "sessions": [
            {
                "id": s.id[:8] if s.id else "",
                "full_id": s.id,
                "date": s.start_date[:10] if s.start_date else "",
                "surface": s.surface,
                "tags": s.tags,
                "title": s.title,
            }
            for s in sessions
        ],
        "count": len(sessions),
    }

    if show_stats:
        result["stats"] = db.get_inspect_stats()

    return result


@mcp.tool(title="Get Usage Stats")
def get_stats() -> dict:
    """Return a usage dashboard: session counts by surface, project, and tag;
    storage metrics (DB size, estimated tokens stored); and the 5 most recent sessions.

    Provides visibility into your memory usage -- who saved what, how much is stored,
    and what's been captured most recently.
    """
    return db.get_usage_stats()


@mcp.tool(title="Consolidate Memories")
def consolidate_memories(
    project: str,
    surface: str | None = None,
    max_sessions: int = 50,
    mode: str = "heuristic",
) -> dict:
    """Run memory consolidation for a project to build a structured digest.

    Analyzes recent sessions and extracts decisions, open questions, and tech
    stack facts. Free tier: up to 3 consolidations per day. Pro: unlimited.

    Returns a digest dict with status, decisions found, open questions, and
    the formatted digest_markdown for reference.

    Acquires an exclusive lock; returns status='lock_held' if another
    consolidation is already running.

    Args:
        project: Project name (matches the --project tag used when saving sessions)
        surface: Surface to consolidate ('code', 'cowork', 'chat', etc.) or None for all
        max_sessions: Maximum number of recent sessions to analyze (default 50)
        mode: 'heuristic' (free, default). 'llm' requires Pro (v0.6.1).
    """
    from core.consolidation import HeuristicConsolidator
    import pathlib
    lore_dir = str(pathlib.Path(db.config.db_path).parent)
    consolidator = HeuristicConsolidator(lore_dir=lore_dir)
    result = consolidator.consolidate(
        project=project,
        surface=surface,
        db=db,
        max_sessions=max_sessions,
        mode="heuristic",  # LLM mode deferred to v0.6.1
        is_pro=db.config.is_pro,
        trigger="on-demand",
    )
    return result


@mcp.tool(title="Get Memory Digest")
def get_memory_digest(
    project: str,
    surface: str | None = None,
    disable: bool | None = None,
) -> dict:
    """Retrieve the current memory digest for a project without re-running consolidation.

    Returns None if no digest exists. Use consolidate_memories first to generate one.

    Optionally set disable=True to suppress auto-load injection for this digest,
    or disable=False to re-enable injection. Omit disable to just read the current state.

    Args:
        project: Project name
        surface: Surface filter (or None for all)
        disable: If provided, update the disabled flag on the digest
    """
    if disable is not None:
        db.update_digest_disabled(project, surface, disabled=disable)
    digest = db.get_memory_digest(project, surface)
    if digest is None:
        return {
            "status": "no_digest",
            "message": "No memory digest found. Run consolidate_memories to generate one.",
            "project": project,
            "surface": surface,
        }
    return {
        "status": "ok",
        "project": digest["project"],
        "surface": digest["surface"],
        "mode": digest.get("mode", "heuristic"),
        "source_count": digest.get("source_count", 0),
        "updated_at": digest.get("updated_at", ""),
        "disabled": bool(digest.get("disabled", 0)),
        "digest_markdown": digest.get("digest_markdown", ""),
        "decisions": digest.get("decisions"),
        "open_questions": digest.get("open_questions"),
        "known_stack": digest.get("known_stack"),
    }


@mcp.tool(title="Set Session Expiry")
def set_session_expiry(
    session_id: str,
    expires_at: str | None,
) -> dict:
    """Set or clear an expiry date on a session.

    After expires_at, the session is excluded from default search and auto-load.
    The session is NOT deleted -- recover it with search_sessions(include_expired=True).
    Pass expires_at=None to clear a previously set expiry.

    Args:
        session_id: ID of the session to update
        expires_at: ISO 8601 date string (e.g. '2027-01-01T00:00:00Z'), or None to clear
    """
    found = db.set_session_expiry(session_id, expires_at)
    if not found:
        return {"status": "not_found", "session_id": session_id}
    return {
        "status": "ok",
        "session_id": session_id,
        "expires_at": expires_at,
    }


@mcp.tool(title="Get Dream Log")
def get_dream_log(
    project: str | None = None,
    surface: str | None = None,
    limit: int = 10,
) -> dict:
    """Return recent consolidation log entries for transparency and diagnostics.

    Each entry shows: timestamp, project, surface, mode, source_count, trigger.
    Use this to confirm consolidation ran, check rate limit status, and diagnose
    fallbacks (e.g. api_key_found=false for LLM-mode fallback).

    Args:
        project: Filter by project (or None for all projects)
        surface: Filter by surface (or None for all)
        limit: Maximum number of entries to return (default 10, newest first)
    """
    import pathlib
    lore_dir = pathlib.Path(db.config.db_path).parent
    log_path = str(lore_dir / "consolidation.log")
    entries = db.get_consolidation_log_entries(
        project=project,
        surface=surface,
        limit=limit,
        log_path=log_path,
    )
    digest = None
    if project:
        raw = db.get_memory_digest(project, surface)
        if raw:
            inject_env = os.environ.get("LORECONVO_DREAM_INJECT", "true").lower()
            inject_active = inject_env != "false" and not bool(raw.get("disabled", 0))
            digest = {
                "updated_at": raw.get("updated_at", ""),
                "mode": raw.get("mode", "heuristic"),
                "source_count": raw.get("source_count", 0),
                "disabled": bool(raw.get("disabled", 0)),
                "api_key_found": bool(raw.get("api_key_found", 1)),
                "injection_active": inject_active,
                "injection_reason": (
                    "active" if inject_active
                    else ("LORECONVO_DREAM_INJECT=false" if inject_env == "false"
                          else "digest.disabled=1 -- manually suppressed")
                ),
            }
    return {
        "status": "ok",
        "project": project,
        "surface": surface,
        "entries": entries,
        "digest_status": digest,
    }


def main():
    """Entry point for uvx / console script execution."""
    mcp.run(transport="stdio")


if __name__ == "__main__":
    main()
